### ISSUE TITLE
gatsby develops exits without error

### ISSUE THREAD

**Issue by vbdane** [bagseye/barcadia#17]
I cloned this respository, imported the example-config.json into contentful using the appropriate management key, placed space ID and delivery API key into the environment variables and then ran `gatsby develop` but the terminal exits after this message:
```
success load gatsby config - 0.065s
success load plugins - 2.930s
success onPreInit - 0.011s
success initialize cache - 0.640s
success copy gatsby files - 0.790s
success Compiling Gatsby Functions - 0.457s
success onPreBootstrap - 0.504s
success createSchemaCustomization - 0.915s
success Contentful: Sync all items - 0.656s - 39/39 59.48/s
info Contentful: 15 new/updated entries
info Contentful: 0 deleted entries
info Contentful: 0 cached entries
info Contentful: 24 new/updated assets
info Contentful: 0 cached assets
info Contentful: 0 deleted assets
success Contentful: Fetch data (fy77mx0i50hq-master) - 5.326s
info Creating 3 Contentful Page nodes
info Creating 4 Contentful Post nodes
info Creating 5 Contentful Product nodes
info Creating 3 Contentful FAQ nodes
info Creating 24 Contentful asset nodes
success Contentful: Create nodes (MYSPACEID-master) - 0.917s
success Contentful: Process data (MYSPACEID-master) - 0.973s
success Checking for changed pages - 0.003s
success source and transform nodes - 6.537s
success building schema - 0.743s
success createPages - 0.002s
success createPagesStatefully - 0.242s
info Total nodes: 79, SitePage nodes: 17 (use --verbose for breakdown)
success Checking for changed pages - 0.003s
success write out redirect data - 0.004s
success onPostBootstrap - 0.004s
info bootstrap finished - 19.065s
success onPreExtractQueries - 0.001s
⠦ extract queries from components
c:\dev\lmdb-store\dependencies\lmdb\libraries\liblmdb\mdb.c:4422: Assertion 'i == x' failed in mdb_txn_commit()
```
I am clueless about what the error is let alone how to resolve it. Any help is appreciated.

**Comment by bagseye** [comment]
Can you confirm what version of Gatsby you have on your machine, as well as node/npm versions

**Comment by vbdane** [comment]
Gatsby-CLI version 4.8.1
Node version 16.3.2

**Comment by bagseye** [comment]
Looking at the error there appears to be a problem in the dependancies. However, I cannot replicate this. 

I've run it on Node versions 14.15.0 - 16.3.0 - 16.14.0 - All with no issues. When I attempted to use 16.3.2 in nvm it did not find this version, and I do not seem to be able to find this version on the NodeJS change log. 

It looks like there is an issue with your setup that is causing these problems and I would suggest running a different version of Node. As mentioned, it appears to run without any issue on the the current LTS version 16.14.0
