### ISSUE TITLE
Just completely broken

### ISSUE THREAD

**Issue by jbwhaley** [bagseye/barcadia#45]
Broken dependency links, deprecated API calls, this list goes on and on...this theme will not build in 2024, don't waste your time with it.

**Comment by bagseye** [comment]
Hey Jarrod!

Thanks for your input it’s much appreciated Jarrod!

Here’s a novel idea Jarrod, have a go at building and maintaining a repo yourself and see how you get on Jarrod! Maybe have a go at fixing some errors Jarrod! 

You have a great day Jarrod!

❤️

**Comment by jbwhaley** [comment]
This was not a personal insult, just a statement of fact. Telling me to go run my own repo is not going to help anyone. Telling people who don't have time to debug your code for you that the theme doesn't work might not be helpful to you, but it might be helpful to someone who doesn't want to waste their time on this the way I did.

I am looking at a template / starter in the first place because I don't have the resources to do a ton of manual work. I certainly don't have the time to debug this theme whose last commit was two years ago.
